site_name: Donkey Car
theme: readthedocs

repo_url: https://github.com/tawnkramer/donkey
edit_uri: edit/master/docs
extra_css: 
    - extra.css

pages:
    - Home: index.md
    - User Guide:
        - 'Build a car': guide/build_hardware.md
        - 'Install the software': guide/install_software.md
        - 'Customize Your Donkey Car OS Install': guide/customize_your_donkey_car_os_install.md
        - 'Get driving': guide/get_driving.md
        - 'Calibrate steering and throttle': guide/calibrate.md
        - 'Train an autopilot': guide/train_autopilot.md
        - 'Donkey Simulator': guide/simulator.md
    - Parts: 
        - 'About': parts/about.md
        - 'Actuators': parts/actuators.md
        - 'Controllers': parts/controllers.md
        - 'Stores': parts/stores.md
        - 'IMU': parts/imu.md
    - Utilities:
        - 'donkey': utility/donkey.md

    - Contribute : contribute.md
    - Tests : tests.md
    - Releases : release.md
    - FAQ : faq.md
