version: '2'

services:

  # Minio - host your own s3 server
  # https://minio.io/
  dcminio:
    container_name: "dcminio"
    hostname: "dcminio"
    image: minio/minio:latest
    ports:
      - "9001:9000"
    environment:
      # https://github.com/minio/minio/blob/master/docs/config/README.md
      # export AWS_ACCESS_KEY_ID=pi
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      # export AWS_SECRET_ACCESS_KEY=123321
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      # Mac OS X users please set up
      # /data/minio/data as a mountable volume
      - /data/dc/minio:/data
    command: "server /data"
